package com.m391.primavera.utils

object Constants {
    const val WATCHES = "Watches"
    const val INVALID_CODE = "Wrong OTP"
    const val IMAGES = "Images"
    const val SUCCESS = "Success"
    const val TEACHER_UID = "teacherUID"
    const val FATHER_UID = "fatherUID"
    const val FATHER_FIRST_NAME = "firstName"
    const val FATHER_LAST_NAME = "lastName"
    const val CHILD_ACADEMIC_YEAR = "academicYear"
    const val CHILD_WATCH_UID = "watchUID"
    const val CHILD_AGE = "age"
    const val CHILD_NAME = "name"
    const val CHILD_UID = "childUID"
    const val IMAGE_PATH = "imagePath"
    const val IMAGE_URI = "imageUri"
    const val FATHER_PHONE = "phone"
    const val ONE_MEGABYTE: Long = 1024 * 1024
    const val CODE_SENT = "Code Sent"
    const val EMPTY_OTP = "Please Enter OTP"
    const val SUCCESSFUL_LOGIN = "Successful Login"
    const val DONE = "Done"
    const val PERMISSION_SETTING = "You need to allow necessary permissions in Settings manually"
    const val PERMISSION_LIST = "Core fundamental are based on these permissions"
    const val PERMISSION_OK = "OK"
    const val PERMISSION_CANCEL = "Cancel"
    const val CHILDREN = "Children"
    const val FATHER = "Father"
    const val TEACHERS = "Teachers"
    const val ERROR = "ERROR"
    const val TEACHER = "Teacher"
    const val NO = "NO"
    const val YES = "YES"
    const val FATHERS = "Fathers"
    const val TEACHER_ACADEMIC_YEARS = "academicYears"
    const val TEACHERS_SUBJECTS = "subjects"
    const val LATITUDE = "Latitude"
    const val LONGITUDE = "Longitude"
    const val BOTH = "Both"
}